### ISSUE TITLE
Vector support for On-Prem SQL Server

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/azure-sql-db-vector-search#5]
Hello,

Is Vector type supported in on-prem SQL Server (Or Azure SQL Server emulator) aswel or is it only available for Azure SQL?

My concern is how to test this feature locally?

Thanks

**Comment by Pookam90** [comment]
> Hello,
> 
> Is Vector type supported in on-prem SQL Server (Or Azure SQL Server emulator) aswel or is it only available for Azure SQL?
> 
> My concern is how to test this feature locally?
> 
> Thanks

The Vector Type is not yet supported in on-prem SQL Server. This is only available for Azure SQL and MI (versionless) as it is in Private preview currently. If you have a specific requirement. You can email me at pookam@microsoft.com

**Comment by yorek** [comment]
That is now been announced that it will available in SQL Server 2025! :)
